account/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_user, name='signup'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout')
]

articles/urls.py
from . import views
from django.conf.urls import url

app_name = 'articles'
urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'create/', views.create_article, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='details'),
]

theblog/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('articles.urls')),
    url(r'^account/', include('account.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=120)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:60]

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb', ]

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:articles')
    else:
        form = UserCreationForm()
    return render(request, 'account/signup.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('articles:articles')
    else:
        form = AuthenticationForm()
    return render(request, 'account/login.html', {'form': form})


def logout_user(request):
    if request.method == "POST":
        logout(request)
        return redirect('articles:articles')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from . import forms
from django.contrib.auth.decorators import login_required


def articles(request):
    article = Article.objects.all().order_by('date')

    return render(request, 'articles/articles.html', {'articles': article[::-1]})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url='/account/login/')
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('articles:articles')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/new_article.html', {'form': form})

articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}
{% block content %}
    <div class="article-detail">
        <div class="article">
            <img src="{{article.thumb.url}}" alt="">
            <h2>{{article.title}}</h2>
            <p>{{article.body}}</p>
            <p>{{article.date}}</p>
        </div>
    </div>
{% endblock %}

articles/templates/articles/articles.html
{% extends 'base_layout.html'%}


{% block content %}
<h1>All articles</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">

        <h3><a href="{% url 'articles:details' article.slug %}">{{article.title}}</a></h3>
        <p>{{article.snippet}} ...</p>
        <p>{{article.date}}</p>
        <p class="author">By: {{article.author.username}}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

articles/templates/articles/new_article.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

articles/templates/base_layout.html
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>articles</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock %}

</head>
<body>
<header class="wrapper">
   <h1><a href="{% url 'articles:articles' %}">Blog B</a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li>
                    <form action="{% url 'accounts:logout'%}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>

                    </form>
                </li>
                <li><a href="{% url 'articles:create'%}" class="highlight">Create Article</a></li>
                {%else%}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {%endif%}
            </ul>
        </nav>
    </header>
<div class="wrapper">
    {% block content %}

    {% endblock %}
</div>

{% block scripts %}
{% endblock %}
</body>
</html>